### ISSUE TITLE
Warning: Unexpected input(s) 'debvers'

### ISSUE THREAD

**Issue by ennorehling** [TykTechnologies/packagecloud-action#3]
The README mentions a "debvers" input that isn't supported?
```
Required Space separated list of Debian based distro versions to push to. The distro version strings are as per
```

providing it results in:
Warning: Unexpected input(s) 'debvers', valid inputs are ['entryPoint', 'args', 'repo', 'dir']

**Comment by ennorehling** [comment]
NB: This is when using TykTechnologies/packagecloud-action@v1
I notice there is a commit from Jan 20 that adds this variable, that seems to not be part of this version?

**Comment by alephnull** [comment]
Yeah, it was added in a later version. 
TBH, we do not use this action anymore. Happy to review PRs though.
